sonar.projectKey=ubook_app
sonar.projectName=Flutter App
sonar.projectVersion=1.0

sonar.sources=lib
sonar.tests=test
sonar.exclusions=**/*.g.dart, build/**
sonar.sourceEncoding=UTF-8

# Muy importante: apunta al servidor local
sonar.host.url=http://localhost:9000