// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-X8xd8jOFd4cq3apQtZrcNR_X2tMYdWk',
    appId: '1:52724083703:web:163c0b4af88971f94a9cf2',
    messagingSenderId: '52724083703',
    projectId: 'ubook-sql',
    authDomain: 'ubook-sql.firebaseapp.com',
    storageBucket: 'ubook-sql.firebasestorage.app',
    measurementId: 'G-9QYK492FGT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUCnwpNra4Nk3faGLK3O0yts678ZAQmjc',
    appId: '1:342045930924:android:bdd2eed9029bba9cabb609',
    messagingSenderId: '342045930924',
    projectId: 'ubook-82861',
    storageBucket: 'ubook-82861.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADGJTXmWw1KdAVTpEIoVierBvf_xDIMkU',
    appId: '1:342045930924:ios:227e15310c5dd142abb609',
    messagingSenderId: '342045930924',
    projectId: 'ubook-82861',
    storageBucket: 'ubook-82861.firebasestorage.app',
    iosBundleId: 'com.example.ubookApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADGJTXmWw1KdAVTpEIoVierBvf_xDIMkU',
    appId: '1:342045930924:ios:227e15310c5dd142abb609',
    messagingSenderId: '342045930924',
    projectId: 'ubook-82861',
    storageBucket: 'ubook-82861.firebasestorage.app',
    iosBundleId: 'com.example.ubookApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBK7WLyd271CBIR2vfoAPN6LNrUyX05Tws',
    appId: '1:342045930924:web:c827c4b12d501b87abb609',
    messagingSenderId: '342045930924',
    projectId: 'ubook-82861',
    authDomain: 'ubook-82861.firebaseapp.com',
    storageBucket: 'ubook-82861.firebasestorage.app',
    measurementId: 'G-W9EQDPXDES',
  );
}
